---
title: "Part 1 ~ stringr functions"
author: "AJ Zekanoski"
date: "2/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Detect string patterns with `str_detect()`

```{r}
vec <- c(" A Unicorn     Fish", "add    Cornmeal", "French Fries   ", "  Acorn  Squash")

str_detect(vec, pattern = "corn")
```

```{r}
walk_subset <- starwars %>% 
  filter(str_detect(name, pattern = "walk"))

# Use str_subset()
```

### Replace a string pattern with something else


`str_replace()` to replace an existing string pattern with something else.

```{r}
vec_bren <- str_replace(vec, pattern = "corn", replacement = "COOL")
vec_bren
```

replace the pattern "Sky" with the pattern "TORNADO"

```{r}
sw_tornado <- starwars %>% 
  mutate(name = str_replace(name, pattern = "Sky", replacement = "TORNADO"))

sw_tornado
```

## Use `str_trim` to remove excess leading and trailing whitespace

```{r}
str_trim(vec)

str_squish(vec)
```

- `str_to_*()`


```{r}
str_to_lower(vec)
```

Using these in combination

```{r}
sw_combo <- starwars %>% 
  filter(str_detect(name, pattern = "Darth")) %>% 
  mutate(name = str_replace(name, pattern = "Darth", replacement = "LLAMA")) %>% 
  mutate(name = str_to_lower(name))

```

